version: '3'
services:
  mtlynchio:
    image: mtlynch/jekyll
    container_name: mtlynch-io-container
    command: bash /app/script/_install.sh
    environment:
      - JEKYLL_ENV=docker
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - ./:/app
